[[redirects]]
from = "/*"
to = "/"
status = 200

[[plugins]]
package = "/plugins/netlify/env"

[build.environment]
# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
REACT_APP_MAIN_ENVIRONMENT = "ALPHA" # used to determine which SCROLL_ENVIRONMENT is to be treated as the main/production one
REACT_APP_ETH_SYMBOL = "ETH"
REACT_APP_BRIDGE_API_PREFIX = "/bridgehistory/api"
REACT_APP_ROLLUPSCAN_API_PREFIX = "/rollupscan/api"
REACT_APP_PREFIX_CLS = "scroll"
REACT_APP_TWITTER_CILENT_ID = "aGhZakRUNU1jbWg1MlgtWlpPaXI6MTpjaQ"
REACT_APP_CODE_CHALLENGE_METHOD = "S256"
REACT_APP_SENTRY_AUTH_TOKEN = "fbd61f0af5c74fb88d27929e8c0975418d148773f17540ec8d663df19f85cf34"
REACT_APP_SENTRY_DSN = "https://791d7df9132d46a9868de0863bd6583c@o4504371258785792.ingest.sentry.io/4504371261079552"
REACT_APP_GOOGLE_ANALYTICS_ID = "G-XR3MGVSHFC"
REACT_APP_CHAIN_ID_L1 = "5"
REACT_APP_EXTERNAL_RPC_URI_L1 = "https://endpoints.omniatech.io/v1/eth/goerli/public"
REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "https://goerli.etherscan.io"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xeF37207c1A1efF6D6a9d7BfF3cF4270e406d319b"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0xe5E30E7c24e4dFcb281A682562E53154C15D3332"
REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"

[context.deploy-preview.environment]
# same as develop
REACT_APP_SCROLL_ENVIRONMENT = "STAGING"
REACT_APP_CHAIN_ID_L2 = "5343531"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://staging-alpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://staging-alpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://staging-blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "IW8if8HhOkWNxAbbuOPCVV-xmzgTvrR4a8wPt6ezoBg"
REACT_APP_STATE = "WpfJ7RU8ICP68JYj28sNJKeUTqV8YmP"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xdbc0f65a2e1A3A76bc468c9CC7D3bbC4002fE035"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x8B4B79C9853ebeC11f58f14b91F0e3aAeDf17D66"
REACT_APP_L2_UNIV2_ADDRESS = "0xa6cc5d4bc2d197bf38d71c1c21c42d428bac325c"
REACT_APP_UNIV2_FACTORY_ADDR = "0xc4FCB3C1DDB7e65c9f59171b438669F870aA9b6e"
REACT_APP_ROUTER_ADDRESS = "0xd77Ad2D008936c482f05cE1936829385ea55C776"
REACT_APP_MULTICALL_ADDR = "0xE3c0cC31695b2112c29E5261df794088521cc64f"
REACT_APP_L2_WETH_ADDRESS = "0x4d5d1747a404e7AC4Cf5e173Ef192c2A0c8d1B12"

[context.develop.environment]
# same as deploy-preview
REACT_APP_SCROLL_ENVIRONMENT = "STAGING"
REACT_APP_CHAIN_ID_L2 = "5343531"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://staging-alpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://staging-alpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://staging-blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "IW8if8HhOkWNxAbbuOPCVV-xmzgTvrR4a8wPt6ezoBg"
REACT_APP_STATE = "WpfJ7RU8ICP68JYj28sNJKeUTqV8YmP"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xdbc0f65a2e1A3A76bc468c9CC7D3bbC4002fE035"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x8B4B79C9853ebeC11f58f14b91F0e3aAeDf17D66"
REACT_APP_L2_UNIV2_ADDRESS = "0xa6cc5d4bc2d197bf38d71c1c21c42d428bac325c"
REACT_APP_UNIV2_FACTORY_ADDR = "0xc4FCB3C1DDB7e65c9f59171b438669F870aA9b6e"
REACT_APP_ROUTER_ADDRESS = "0xd77Ad2D008936c482f05cE1936829385ea55C776"
REACT_APP_MULTICALL_ADDR = "0xE3c0cC31695b2112c29E5261df794088521cc64f"
REACT_APP_L2_WETH_ADDRESS = "0x4d5d1747a404e7AC4Cf5e173Ef192c2A0c8d1B12"

[context.alpha.environment]
# same as main
REACT_APP_SCROLL_ENVIRONMENT = "ALPHA"
REACT_APP_CHAIN_ID_L2 = "534353"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://alpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://alpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "1W2y6F72ulLxiFoEaVKgVDukwEsiOOyH7wSXw0quEbM"
REACT_APP_STATE = "KCVfk8zv-r4t4fef"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xB878F37BB278bf0e4974856fFe86f5e6F66BD725"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x6d79Aa2e4Fbf80CF8543Ad97e294861853fb0649"
REACT_APP_L2_UNIV2_ADDRESS = "0xcb081e15ead7004d4e32d757d919ee07e8fb8af1"
REACT_APP_UNIV2_FACTORY_ADDR = "0x50751a67a4423594260C5D400D0120232608417f"
REACT_APP_ROUTER_ADDRESS = "0x79d6F4BD5267B44a3028DcF6dCD90F55ba18F2c9"
REACT_APP_MULTICALL_ADDR = "0xA1281be5BfF2b4e1b25b1ACAf5B76dBA4ECDbD5C"
REACT_APP_L2_WETH_ADDRESS = "0x2b17A0Da68382C4B7DEC16Ea6998057a444817e6"
REACT_APP_L2_GAS_PRICE_ORACLE = "0x37D61987d0281Fb17DE079C9B8E56B367b1800c4"
