[[redirects]]
from = "/*"
to = "/"
status = 200

# we use content based hash for filenames
# 31536000 is 1 year, recommended by cra
# cra doc https://create-react-app.dev/docs/production-build/
[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "max-age=31536000"

[[plugins]]
package = "/plugins/netlify/env"

[build.environment]
# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
NEXT_PUBLIC_MAIN_ENVIRONMENT = "Mainnet" # used to determine which SCROLL_ENVIRONMENT is to be treated as the main/production one
NEXT_PUBLIC_ETH_SYMBOL = "ETH"
NEXT_PUBLIC_PREFIX_CLS = "scroll"
NEXT_PUBLIC_SENTRY_DSN = "https://791d7df9132d46a9868de0863bd6583c@o4504371258785792.ingest.sentry.io/4504371261079552"
NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-XR3MGVSHFC"
NEXT_PUBLIC_CONNECT_WALLET_PROJECT_ID = "14efbaafcf5232a47d93a68229b71028"
NEXT_PUBLIC_UNIFRA_API_KEY = "9d431c1c-d717-4931-9595-ad0b3a246d13"
NEXT_PUBLIC_NFT_VIEWER_URL="https://nft.scroll.io"
NEXT_PUBLIC_NFT_API_URI="https://nft.scroll.io"


[context.deploy-preview.environment]
NEXT_PUBLIC_SCROLL_ENVIRONMENT = "Staging"
NEXT_PUBLIC_API_BASE_URI = "https://sepolia-api.scroll.io"
NEXT_PUBLIC_BRIDGE_API_URI = "https://sepolia-api-bridge-v2.scroll.io/api"
NEXT_PUBLIC_ROLLUPSCAN_API_URI = "https://sepolia-api-re.scroll.io/api"
NEXT_PUBLIC_CHAIN_ID_L1 = "11155111"
NEXT_PUBLIC_CHAIN_ID_L2 = "534351"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L1 = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L2 = "https://sepolia-rpc.scroll.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L1 = "https://sepolia.etherscan.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L2 = "https://sepolia.scrollscan.com"
NEXT_PUBLIC_L2_SCAN_URI = "https://scroll-sepolia.l2scan.co"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_DORA = "https://www.ondora.xyz/network/scroll-sepolia"
NEXT_PUBLIC_ETHERSCAN_L2 = "https://sepolia.scrollscan.com"
NEXT_PUBLIC_L2_SWAP_URI = "https://uniswap-showcase.sepolia.scroll.xyz/"
NEXT_PUBLIC_L1_ETH_GATEWAY_PROXY_ADDR = "0x8A54A2347Da2562917304141ab67324615e9866d"
NEXT_PUBLIC_L2_ETH_GATEWAY_PROXY_ADDR = "0x91e8ADDFe1358aCa5314c644312d38237fC1101C"
NEXT_PUBLIC_L1_WETH_GATEWAY_PROXY_ADDR = "0x3dA0BF44814cfC678376b3311838272158211695"
NEXT_PUBLIC_L2_WETH_GATEWAY_PROXY_ADDR = "0x481B20A927206aF7A754dB8b904B052e2781ea27"
NEXT_PUBLIC_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x31C994F2017E71b82fd4D8118F140c81215bbb37"
NEXT_PUBLIC_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x058dec71E53079F9ED053F3a0bBca877F6f3eAcf"
NEXT_PUBLIC_L1_USDC_GATEWAY_PROXY_ADDR = ""
NEXT_PUBLIC_L2_USDC_GATEWAY_PROXY_ADDR= ""
NEXT_PUBLIC_L1_DAI_GATEWAY_PROXY_ADDR = "0x8b0B9c4e9f41b9bbDEfFee24F9f11C328093d248"
NEXT_PUBLIC_L2_DAI_GATEWAY_PROXY_ADDR = "0xbF28c28490988026Dca2396148DE50136A54534e"
NEXT_PUBLIC_L1_LIDO_GATEWAY_PROXY_ADDR = "0xF22B24fa7c3168f30b17fd97b71bdd3162DDe029"
NEXT_PUBLIC_L2_LIDO_GATEWAY_PROXY_ADDR = "0x635B054A092F6aE61Ce0Fddc397A704F6626510D"
NEXT_PUBLIC_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x65D123d6389b900d954677c26327bfc1C3e88A13"
NEXT_PUBLIC_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xaDcA915971A336EA2f5b567e662F5bd74AEf9582"
NEXT_PUBLIC_L1_SCROLL_MESSENGER = "0x50c7d3e7f7c656493D1D76aaa1a836CedfCBB16A"
NEXT_PUBLIC_L2_SCROLL_MESSENGER = "0xBa50f5340FB9F3Bd074bD638c9BE13eCB36E603d"
NEXT_PUBLIC_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x13FBE0D0e5552b8c9c4AE9e2435F38f37355998a"
NEXT_PUBLIC_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x9aD3c5617eCAa556d6E166787A97081907171230"
NEXT_PUBLIC_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
NEXT_PUBLIC_L2_GAS_PRICE_ORACLE = "0x247969F4fad93a33d4826046bc3eAE0D36BdE548"
NEXT_PUBLIC_SCROLL_CHAIN = "0x2D567EcE699Eabe5afCd141eDB7A4f2D0D6ce8a0"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT="0x90a274D591d5AB1a25f0DD0F06F28533C34D7d9f"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT_V2="0xDd7d857F570B0C211abfe05cd914A85BefEC2464"
NEXT_PUBLIC_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE="0xF0B2293F5D834eAe920c6974D50957A1732de763"

[context.staging.environment]
NEXT_PUBLIC_SCROLL_ENVIRONMENT = "Staging"
NEXT_PUBLIC_API_BASE_URI = "https://sepolia-api.scroll.io"
NEXT_PUBLIC_BRIDGE_API_URI = "https://sepolia-api-bridge-v2.scroll.io/api"
NEXT_PUBLIC_ROLLUPSCAN_API_URI = "https://sepolia-api-re.scroll.io/api"
NEXT_PUBLIC_CHAIN_ID_L1 = "11155111"
NEXT_PUBLIC_CHAIN_ID_L2 = "534351"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L1 = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L2 = "https://sepolia-rpc.scroll.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L1 = "https://sepolia.etherscan.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L2 = "https://sepolia.scrollscan.com"
NEXT_PUBLIC_L2_SCAN_URI = "https://scroll-sepolia.l2scan.co"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_DORA = "https://www.ondora.xyz/network/scroll-sepolia"
NEXT_PUBLIC_ETHERSCAN_L2 = "https://sepolia.scrollscan.com"
NEXT_PUBLIC_L2_SWAP_URI = "https://uniswap-showcase.sepolia.scroll.xyz/"
NEXT_PUBLIC_L1_ETH_GATEWAY_PROXY_ADDR = "0x8A54A2347Da2562917304141ab67324615e9866d"
NEXT_PUBLIC_L2_ETH_GATEWAY_PROXY_ADDR = "0x91e8ADDFe1358aCa5314c644312d38237fC1101C"
NEXT_PUBLIC_L1_WETH_GATEWAY_PROXY_ADDR = "0x3dA0BF44814cfC678376b3311838272158211695"
NEXT_PUBLIC_L2_WETH_GATEWAY_PROXY_ADDR = "0x481B20A927206aF7A754dB8b904B052e2781ea27"
NEXT_PUBLIC_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x31C994F2017E71b82fd4D8118F140c81215bbb37"
NEXT_PUBLIC_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x058dec71E53079F9ED053F3a0bBca877F6f3eAcf"
NEXT_PUBLIC_L1_USDC_GATEWAY_PROXY_ADDR = ""
NEXT_PUBLIC_L2_USDC_GATEWAY_PROXY_ADDR= ""
NEXT_PUBLIC_L1_DAI_GATEWAY_PROXY_ADDR = "0x8b0B9c4e9f41b9bbDEfFee24F9f11C328093d248"
NEXT_PUBLIC_L2_DAI_GATEWAY_PROXY_ADDR = "0xbF28c28490988026Dca2396148DE50136A54534e"
NEXT_PUBLIC_L1_LIDO_GATEWAY_PROXY_ADDR = "0xF22B24fa7c3168f30b17fd97b71bdd3162DDe029"
NEXT_PUBLIC_L2_LIDO_GATEWAY_PROXY_ADDR = "0x635B054A092F6aE61Ce0Fddc397A704F6626510D"
NEXT_PUBLIC_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x65D123d6389b900d954677c26327bfc1C3e88A13"
NEXT_PUBLIC_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xaDcA915971A336EA2f5b567e662F5bd74AEf9582"
NEXT_PUBLIC_L1_SCROLL_MESSENGER = "0x50c7d3e7f7c656493D1D76aaa1a836CedfCBB16A"
NEXT_PUBLIC_L2_SCROLL_MESSENGER = "0xBa50f5340FB9F3Bd074bD638c9BE13eCB36E603d"
NEXT_PUBLIC_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x13FBE0D0e5552b8c9c4AE9e2435F38f37355998a"
NEXT_PUBLIC_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x9aD3c5617eCAa556d6E166787A97081907171230"
NEXT_PUBLIC_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
NEXT_PUBLIC_L2_GAS_PRICE_ORACLE = "0x247969F4fad93a33d4826046bc3eAE0D36BdE548"
NEXT_PUBLIC_SCROLL_CHAIN = "0x2D567EcE699Eabe5afCd141eDB7A4f2D0D6ce8a0"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT="0x90a274D591d5AB1a25f0DD0F06F28533C34D7d9f"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT_V2="0xDd7d857F570B0C211abfe05cd914A85BefEC2464"
NEXT_PUBLIC_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE="0xF0B2293F5D834eAe920c6974D50957A1732de763"

[context.sepolia.environment]
NEXT_PUBLIC_SCROLL_ENVIRONMENT = "Sepolia"
NEXT_PUBLIC_API_BASE_URI = "https://sepolia-api.scroll.io"
NEXT_PUBLIC_BRIDGE_API_URI = "https://sepolia-api-bridge-v2.scroll.io/api"
NEXT_PUBLIC_ROLLUPSCAN_API_URI = "https://sepolia-api-re.scroll.io/api"
NEXT_PUBLIC_CHAIN_ID_L1 = "11155111"
NEXT_PUBLIC_CHAIN_ID_L2 = "534351"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L1 = "https://ethereum-sepolia.blockpi.network/v1/rpc/public"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L2 = "https://sepolia-rpc.scroll.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L1 = "https://sepolia.etherscan.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L2 = "https://sepolia.scrollscan.com"
NEXT_PUBLIC_L2_SCAN_URI = "https://scroll-sepolia.l2scan.co"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_DORA = "https://www.ondora.xyz/network/scroll-sepolia"
NEXT_PUBLIC_ETHERSCAN_L2 = "https://sepolia.scrollscan.com"
NEXT_PUBLIC_L2_SWAP_URI = "https://uniswap-showcase.sepolia.scroll.xyz/"
NEXT_PUBLIC_L1_ETH_GATEWAY_PROXY_ADDR = "0x8A54A2347Da2562917304141ab67324615e9866d"
NEXT_PUBLIC_L2_ETH_GATEWAY_PROXY_ADDR = "0x91e8ADDFe1358aCa5314c644312d38237fC1101C"
NEXT_PUBLIC_L1_WETH_GATEWAY_PROXY_ADDR = "0x3dA0BF44814cfC678376b3311838272158211695"
NEXT_PUBLIC_L2_WETH_GATEWAY_PROXY_ADDR = "0x481B20A927206aF7A754dB8b904B052e2781ea27"
NEXT_PUBLIC_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x31C994F2017E71b82fd4D8118F140c81215bbb37"
NEXT_PUBLIC_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x058dec71E53079F9ED053F3a0bBca877F6f3eAcf"
NEXT_PUBLIC_L1_USDC_GATEWAY_PROXY_ADDR = ""
NEXT_PUBLIC_L2_USDC_GATEWAY_PROXY_ADDR= ""
NEXT_PUBLIC_L1_DAI_GATEWAY_PROXY_ADDR = "0x8b0B9c4e9f41b9bbDEfFee24F9f11C328093d248"
NEXT_PUBLIC_L2_DAI_GATEWAY_PROXY_ADDR = "0xbF28c28490988026Dca2396148DE50136A54534e"
NEXT_PUBLIC_L1_LIDO_GATEWAY_PROXY_ADDR = "0xF22B24fa7c3168f30b17fd97b71bdd3162DDe029"
NEXT_PUBLIC_L2_LIDO_GATEWAY_PROXY_ADDR = "0x635B054A092F6aE61Ce0Fddc397A704F6626510D"
NEXT_PUBLIC_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x65D123d6389b900d954677c26327bfc1C3e88A13"
NEXT_PUBLIC_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xaDcA915971A336EA2f5b567e662F5bd74AEf9582"
NEXT_PUBLIC_L1_SCROLL_MESSENGER = "0x50c7d3e7f7c656493D1D76aaa1a836CedfCBB16A"
NEXT_PUBLIC_L2_SCROLL_MESSENGER = "0xBa50f5340FB9F3Bd074bD638c9BE13eCB36E603d"
NEXT_PUBLIC_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x13FBE0D0e5552b8c9c4AE9e2435F38f37355998a"
NEXT_PUBLIC_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x9aD3c5617eCAa556d6E166787A97081907171230"
NEXT_PUBLIC_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
NEXT_PUBLIC_L2_GAS_PRICE_ORACLE = "0x247969F4fad93a33d4826046bc3eAE0D36BdE548"
NEXT_PUBLIC_SCROLL_CHAIN = "0x2D567EcE699Eabe5afCd141eDB7A4f2D0D6ce8a0"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT="0x90a274D591d5AB1a25f0DD0F06F28533C34D7d9f"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT_V2="0xDd7d857F570B0C211abfe05cd914A85BefEC2464"
NEXT_PUBLIC_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE="0xF0B2293F5D834eAe920c6974D50957A1732de763"

[context.mainnet.environment]
NEXT_PUBLIC_SCROLL_ENVIRONMENT = "Mainnet"
NEXT_PUBLIC_API_BASE_URI = "https://mainnet-api.scroll.io"
NEXT_PUBLIC_BRIDGE_API_URI = "https://mainnet-api-bridge-v2.scroll.io/api"
NEXT_PUBLIC_ROLLUPSCAN_API_URI = "https://mainnet-api-re.scroll.io/api"
NEXT_PUBLIC_CHAIN_ID_L1 = "1"
NEXT_PUBLIC_CHAIN_ID_L2 = "534352"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L1 = "https://ethereum.blockpi.network/v1/rpc/public"
NEXT_PUBLIC_EXTERNAL_RPC_URI_L2 = "https://rpc.scroll.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L1 = "https://etherscan.io"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_L2 = "https://scrollscan.com"
NEXT_PUBLIC_EXTERNAL_EXPLORER_URI_DORA = "https://www.ondora.xyz/network/scroll"
NEXT_PUBLIC_ETHERSCAN_L2 = "https://scrollscan.com"
NEXT_PUBLIC_L2_SCAN_URI = "https://scroll.l2scan.co"
NEXT_PUBLIC_L1_ETH_GATEWAY_PROXY_ADDR = "0x7F2b8C31F88B6006c382775eea88297Ec1e3E905"
NEXT_PUBLIC_L2_ETH_GATEWAY_PROXY_ADDR = "0x6EA73e05AdC79974B931123675ea8F78FfdacDF0"
NEXT_PUBLIC_L1_WETH_GATEWAY_PROXY_ADDR = "0x7AC440cAe8EB6328de4fA621163a792c1EA9D4fE"
NEXT_PUBLIC_L2_WETH_GATEWAY_PROXY_ADDR = "0x7003E7B7186f0E6601203b99F7B8DECBfA391cf9"
NEXT_PUBLIC_L1_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0xb2b10a289A229415a124EFDeF310C10cb004B6ff"
NEXT_PUBLIC_L2_CUSTOM_ERC20_GATEWAY_PROXY_ADDR = "0x64CCBE37c9A82D85A1F2E74649b7A42923067988"
NEXT_PUBLIC_L1_USDC_GATEWAY_PROXY_ADDR = "0xf1AF3b23DE0A5Ca3CAb7261cb0061C0D779A5c7B"
NEXT_PUBLIC_L2_USDC_GATEWAY_PROXY_ADDR = "0x33B60d5Dd260d453cAC3782b0bDC01ce84672142"
NEXT_PUBLIC_L1_DAI_GATEWAY_PROXY_ADDR = "0x67260A8B73C5B77B55c1805218A42A7A6F98F515"
NEXT_PUBLIC_L2_DAI_GATEWAY_PROXY_ADDR = "0xaC78dff3A87b5b534e366A93E785a0ce8fA6Cc62"
NEXT_PUBLIC_L1_LIDO_GATEWAY_PROXY_ADDR = "0x6625C6332c9F91F2D27c304E729B86db87A3f504"
NEXT_PUBLIC_L2_LIDO_GATEWAY_PROXY_ADDR = "0x8aE8f22226B9d789A36AC81474e633f8bE2856c9"
NEXT_PUBLIC_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xD8A791fE2bE73eb6E6cF1eb0cb3F36adC9B3F8f9"
NEXT_PUBLIC_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xE2b4795039517653c5Ae8C2A9BFdd783b48f447A"
NEXT_PUBLIC_L1_SCROLL_MESSENGER = "0x6774Bcbd5ceCeF1336b5300fb5186a12DDD8b367"
NEXT_PUBLIC_L2_SCROLL_MESSENGER = "0x781e90f1c8Fc4611c9b7497C3B47F99Ef6969CbC"
NEXT_PUBLIC_L1_GATEWAY_ROUTER_PROXY_ADDR = "0xF8B1378579659D8F7EE5f3C929c2f3E332E41Fd6"
NEXT_PUBLIC_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x4C0926FF5252A435FD19e10ED15e5a249Ba19d79"
NEXT_PUBLIC_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
NEXT_PUBLIC_L2_GAS_PRICE_ORACLE = "0x987e300fDfb06093859358522a79098848C33852"
NEXT_PUBLIC_SCROLL_CHAIN = "0xa13BAF47339d63B743e7Da8741db5456DAc1E556"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT="0x74670A3998d9d6622E32D0847fF5977c37E0eC91"
NEXT_PUBLIC_SCROLL_ORIGINS_NFT_V2="0x42bCaCb8D24Ba588cab8Db0BB737DD2eFca408EC"
NEXT_PUBLIC_L1_MESSAGE_QUEUE_WITH_GAS_PRICE_ORACLE="0x0d7E906BD9cAFa154b048cFa766Cc1E54E39AF9B"