[[redirects]]
from = "/alpha/*"
to = "/:splat"
status = 301

[[redirects]]
from = "/*"
to = "/"
status = 200

# we use content based hash for filenames
# 31536000 is 1 year, recommended by cra
# cra doc https://create-react-app.dev/docs/production-build/
[[headers]]
for = "/static/*"

[headers.values]
Cache-Control = "max-age=31536000"

[[plugins]]
package = "/plugins/netlify/env"

[build.environment]
# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
REACT_APP_MAIN_ENVIRONMENT = "ALPHA" # used to determine which SCROLL_ENVIRONMENT is to be treated as the main/production one
REACT_APP_ETH_SYMBOL = "ETH"
REACT_APP_BRIDGE_API_PREFIX = "/bridgehistory/api"
REACT_APP_ROLLUPSCAN_API_PREFIX = "/rollupscan/api"
REACT_APP_PREFIX_CLS = "scroll"
REACT_APP_TWITTER_CILENT_ID = "aGhZakRUNU1jbWg1MlgtWlpPaXI6MTpjaQ"
REACT_APP_CODE_CHALLENGE_METHOD = "S256"
REACT_APP_SENTRY_DSN = "https://791d7df9132d46a9868de0863bd6583c@o4504371258785792.ingest.sentry.io/4504371261079552"
REACT_APP_GOOGLE_ANALYTICS_ID = "G-XR3MGVSHFC"
REACT_APP_CHAIN_ID_L1 = "5"
REACT_APP_EXTERNAL_RPC_URI_L1 = "https://rpc.ankr.com/eth_goerli"
REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "https://goerli.etherscan.io"
REACT_APP_EXTERNAL_EXPLORER_URI_UNIFRA = "https://scroll.l2scan.co/"
REACT_APP_EXTERNAL_EXPLORER_URI_DORA = "https://www.ondora.xyz/network/scroll-zkp/"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xeF37207c1A1efF6D6a9d7BfF3cF4270e406d319b"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0xe5E30E7c24e4dFcb281A682562E53154C15D3332"
REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
REACT_APP_CONNECT_WALLET_PROJECT_ID = "14efbaafcf5232a47d93a68229b71028"

[context.alpha-deploy-preview.environment]
# INACTIVE temporarily, same as alpha-staging
REACT_APP_SCROLL_ENVIRONMENT = "STAGING"
REACT_APP_CHAIN_ID_L2 = "5343532222"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://staging-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://staging-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://staging-blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "IW8if8HhOkWNxAbbuOPCVV-xmzgTvrR4a8wPt6ezoBg"
REACT_APP_STATE = "WpfJ7RU8ICP68JYj28sNJKeUTqV8YmP"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x16c1079B27eD9c363B7D08aC5Ae937A398972A5C"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x20625cdf37074Ef7188da6F2138a793Ad349947F"
REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x90271634BCB020e06ea4840C3f7aa61b8F860651"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x37A3FA7Ca7Ae8449059d3faff7a8f710BD7b9D2f"
REACT_APP_L2_WETH_ADDRESS = "0x5300000000000000000000000000000000000004"
REACT_APP_L2_GAS_PRICE_ORACLE = "0x789a11DE6B471272BA5a6231d845533852f446CD"

[context.alpha-staging.environment]
# temporarily use sepolia directly; TODO: revert to using a separate staging env
REACT_APP_SCROLL_ENVIRONMENT = "SEPOLIA"
REACT_APP_CHAIN_ID_L2 = "534351"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://sepolia-rpc.scroll.io"
REACT_APP_API_BASE_URI = "https://sepolia-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://sepolia-blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "1W2y6F72ulLxiFoEaVKgVDukwEsiOOyH7wSXw0quEbM"
REACT_APP_STATE = "KCVfk8zv-r4t4fef"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x28CC694Bb1190c8EC521e5aDAAF5cEA6E30Ed1Fc"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x3146ADB677a01B9488e54eb3ac9EdAaE5504Fc46"
REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x88A59756752854C7A494d76726Df64230Dcf7Ac5"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0xD93c283c7D7de2Ae62F76dc692f4cD72641FC2b7"
REACT_APP_L2_WETH_ADDRESS = "0x5300000000000000000000000000000000000004"
REACT_APP_L2_GAS_PRICE_ORACLE = "0x5525755C10F2e9d8CC11e9092BD5ec073aE56b4B"

[context.deploy-preview.environment]
# temporarily use sepolia directly; TODO: revert to using a separate staging env
REACT_APP_SCROLL_ENVIRONMENT = "SEPOLIA"
REACT_APP_CHAIN_ID_L2 = "534351"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://sepolia-rpc.scroll.io/l2" # TODO: Remove /l2 suffix
REACT_APP_API_BASE_URI = "https://sepolia-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://sepolia-blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "1W2y6F72ulLxiFoEaVKgVDukwEsiOOyH7wSXw0quEbM"
REACT_APP_STATE = "KCVfk8zv-r4t4fef"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x28CC694Bb1190c8EC521e5aDAAF5cEA6E30Ed1Fc"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x3146ADB677a01B9488e54eb3ac9EdAaE5504Fc46"
REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x88A59756752854C7A494d76726Df64230Dcf7Ac5"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0xD93c283c7D7de2Ae62F76dc692f4cD72641FC2b7"
REACT_APP_L2_WETH_ADDRESS = "0x5300000000000000000000000000000000000004"
REACT_APP_L2_GAS_PRICE_ORACLE = "0x5525755C10F2e9d8CC11e9092BD5ec073aE56b4B"

[context.staging.environment]
# temporarily use sepolia directly; TODO: revert to using a separate staging env
REACT_APP_SCROLL_ENVIRONMENT = "SEPOLIA"
REACT_APP_CHAIN_ID_L2 = "534351"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://sepolia-rpc.scroll.io/l2" # TODO: Remove /l2 suffix
REACT_APP_API_BASE_URI = "https://sepolia-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://sepolia-blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "1W2y6F72ulLxiFoEaVKgVDukwEsiOOyH7wSXw0quEbM"
REACT_APP_STATE = "KCVfk8zv-r4t4fef"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x28CC694Bb1190c8EC521e5aDAAF5cEA6E30Ed1Fc"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x3146ADB677a01B9488e54eb3ac9EdAaE5504Fc46"
REACT_APP_L1_GAS_PRICE_ORACLE = "0x5300000000000000000000000000000000000002"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x88A59756752854C7A494d76726Df64230Dcf7Ac5"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0xD93c283c7D7de2Ae62F76dc692f4cD72641FC2b7"
REACT_APP_L2_WETH_ADDRESS = "0x5300000000000000000000000000000000000004"
REACT_APP_L2_GAS_PRICE_ORACLE = "0x5525755C10F2e9d8CC11e9092BD5ec073aE56b4B"

[context.alpha.environment]
# same as main
REACT_APP_SCROLL_ENVIRONMENT = "ALPHA"
REACT_APP_CHAIN_ID_L2 = "534353"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://alpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://alpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://blockscout.scroll.io"
REACT_APP_CODE_CHALLENGE = "1W2y6F72ulLxiFoEaVKgVDukwEsiOOyH7wSXw0quEbM"
REACT_APP_STATE = "KCVfk8zv-r4t4fef"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xB878F37BB278bf0e4974856fFe86f5e6F66BD725"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x6d79Aa2e4Fbf80CF8543Ad97e294861853fb0649"
REACT_APP_L2_UNIV2_ADDRESS = "0xcb081e15ead7004d4e32d757d919ee07e8fb8af1"
REACT_APP_UNIV2_FACTORY_ADDR = "0x50751a67a4423594260C5D400D0120232608417f"
REACT_APP_ROUTER_ADDRESS = "0x79d6F4BD5267B44a3028DcF6dCD90F55ba18F2c9"
REACT_APP_MULTICALL_ADDR = "0xA1281be5BfF2b4e1b25b1ACAf5B76dBA4ECDbD5C"
REACT_APP_L2_WETH_ADDRESS = "0x2b17A0Da68382C4B7DEC16Ea6998057a444817e6"
REACT_APP_L2_GAS_PRICE_ORACLE = "0x37D61987d0281Fb17DE079C9B8E56B367b1800c4"
