# these two redirects are used in MAIN, as a transitional help
[[redirects]]
from = "/l1/*"
to = "https://prealpha-rpc.scroll.io/l1/:splat"
status = 200

[[redirects]]
from = "/l2/*"
to = "https://prealpha-rpc.scroll.io/l2/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/"
status = 200

[[plugins]]
package = "/plugins/netlify/env"

[build.environment]
# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
REACT_APP_ETH_SYMBOL = "TSETH"
REACT_APP_USDC_SYMBOL = "TSUSDC"
REACT_APP_UNI_V2_TOKEN_SYMBOL = "TSUNI2"
REACT_APP_FAUCET_API_PREFIX = "/faucet/api"
REACT_APP_BRIDGE_API_PREFIX = "/bridgehistory/api"
REACT_APP_ROLLUPSCAN_API_PREFIX = "/rollupscan/api"
REACT_APP_PREFIX_CLS = "scroll"
REACT_APP_TWITTER_CILENT_ID = "aGhZakRUNU1jbWg1MlgtWlpPaXI6MTpjaQ"
REACT_APP_CODE_CHALLENGE_METHOD = "S256"
REACT_APP_HCAPTCHA_SITE_KEY = "541838f2-e585-4726-b398-24102b1d4df8"
REACT_APP_SENTRY_AUTH_TOKEN = "fbd61f0af5c74fb88d27929e8c0975418d148773f17540ec8d663df19f85cf34"
REACT_APP_SENTRY_DSN = "https://791d7df9132d46a9868de0863bd6583c@o4504371258785792.ingest.sentry.io/4504371261079552"
REACT_APP_GOOGLE_ANALYTICS_ID = "G-XR3MGVSHFC"

[context.deploy-preview.environment]
# same as staging
REACT_APP_SCROLL_ENVIRONMENT = "STAGING"
REACT_APP_CHAIN_ID_L1 = "5343511"
REACT_APP_CHAIN_ID_L2 = "5343541"
REACT_APP_EXTERNAL_RPC_URI_L1 = "https://staging-prealpha-rpc.scroll.io/l1"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://staging-prealpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://staging-prealpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "https://staging-l1scan.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://staging-l2scan.scroll.io"
REACT_APP_CODE_CHALLENGE = "IW8if8HhOkWNxAbbuOPCVV-xmzgTvrR4a8wPt6ezoBg"
REACT_APP_STATE = "WpfJ7RU8ICP68JYj28sNJKeUTqV8YmP"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x7e28DB599B3410EbBaBF5E27bdCB306b75cfe438"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xdbc0f65a2e1A3A76bc468c9CC7D3bbC4002fE035"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x43c7B43a2FC87A62eb98c009318Eb0fdb2a4611A"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x8B4B79C9853ebeC11f58f14b91F0e3aAeDf17D66"
REACT_APP_L1_USDC_ADDRESS = "0x825f0878cb8c5fa17d5e913de7f9728f90fe6213"
REACT_APP_L2_USDC_ADDRESS = "0x415f01fb0abfb7b9eedc3f746031235f7d0021bc"
REACT_APP_L2_UNIV2_ADDRESS = "0xa6cc5d4bc2d197bf38d71c1c21c42d428bac325c"
REACT_APP_UNIV2_FACTORY_ADDR = "0xc4FCB3C1DDB7e65c9f59171b438669F870aA9b6e"
REACT_APP_ROUTER_ADDRESS = "0xd77Ad2D008936c482f05cE1936829385ea55C776"
REACT_APP_MULTICALL_ADDR = "0xE3c0cC31695b2112c29E5261df794088521cc64f"
REACT_APP_L2_WETH_ADDRESS = "0x4d5d1747a404e7AC4Cf5e173Ef192c2A0c8d1B12"

[context.staging.environment]
REACT_APP_SCROLL_ENVIRONMENT = "STAGING"
REACT_APP_CHAIN_ID_L1 = "5343511"
REACT_APP_CHAIN_ID_L2 = "5343541"
REACT_APP_EXTERNAL_RPC_URI_L1 = "https://staging-prealpha-rpc.scroll.io/l1"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://staging-prealpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://staging-prealpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "https://staging-l1scan.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://staging-l2scan.scroll.io"
REACT_APP_CODE_CHALLENGE = "IW8if8HhOkWNxAbbuOPCVV-xmzgTvrR4a8wPt6ezoBg"
REACT_APP_STATE = "WpfJ7RU8ICP68JYj28sNJKeUTqV8YmP"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x7e28DB599B3410EbBaBF5E27bdCB306b75cfe438"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xdbc0f65a2e1A3A76bc468c9CC7D3bbC4002fE035"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x43c7B43a2FC87A62eb98c009318Eb0fdb2a4611A"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0x8B4B79C9853ebeC11f58f14b91F0e3aAeDf17D66"
REACT_APP_L1_USDC_ADDRESS = "0x825f0878cb8c5fa17d5e913de7f9728f90fe6213"
REACT_APP_L2_USDC_ADDRESS = "0x415f01fb0abfb7b9eedc3f746031235f7d0021bc"
REACT_APP_L2_UNIV2_ADDRESS = "0xa6cc5d4bc2d197bf38d71c1c21c42d428bac325c"
REACT_APP_UNIV2_FACTORY_ADDR = "0xc4FCB3C1DDB7e65c9f59171b438669F870aA9b6e"
REACT_APP_ROUTER_ADDRESS = "0xd77Ad2D008936c482f05cE1936829385ea55C776"
REACT_APP_MULTICALL_ADDR = "0xE3c0cC31695b2112c29E5261df794088521cc64f"
REACT_APP_L2_WETH_ADDRESS = "0x4d5d1747a404e7AC4Cf5e173Ef192c2A0c8d1B12"

[context.main.environment]
REACT_APP_SCROLL_ENVIRONMENT = "MAIN"
REACT_APP_CHAIN_ID_L1 = "534351"
REACT_APP_CHAIN_ID_L2 = "534354"
REACT_APP_EXTERNAL_RPC_URI_L1 = "https://prealpha-rpc.scroll.io/l1"
REACT_APP_EXTERNAL_RPC_URI_L2 = "https://prealpha-rpc.scroll.io/l2"
REACT_APP_API_BASE_URI = "https://prealpha-api.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L1 = "https://l1scan.scroll.io"
REACT_APP_EXTERNAL_EXPLORER_URI_L2 = "https://l2scan.scroll.io"
REACT_APP_CODE_CHALLENGE = "1W2y6F72ulLxiFoEaVKgVDukwEsiOOyH7wSXw0quEbM"
REACT_APP_STATE = "KCVfk8zv-r4t4fef"
REACT_APP_L1_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0xf8F8B383285CD23eD2Cb9FDF9599B968DdafC3C0"
REACT_APP_L2_STANDARD_ERC20_GATEWAY_PROXY_ADDR = "0x330A32FEE6421B9c0b6cFAA6DdAA1AD6C8ED17f9"
REACT_APP_L1_GATEWAY_ROUTER_PROXY_ADDR = "0x47c02B023B6787EF4E503DF42bBB1a94f451a1C0"
REACT_APP_L2_GATEWAY_ROUTER_PROXY_ADDR = "0xD7227113b92E537AeDa220d5A2F201B836E5879D"
REACT_APP_L1_USDC_ADDRESS = "0x1838a36ab91900fa0e637006bB2fAA6Ef1a5f841"
REACT_APP_L2_USDC_ADDRESS = "0x38BA9a208F34Ddc9332f6DfC0E9d567f098958A4"
REACT_APP_L2_UNIV2_ADDRESS = "0xcb081e15ead7004d4e32d757d919ee07e8fb8af1"
REACT_APP_UNIV2_FACTORY_ADDR = "0x182c2e52Abb587229307e35a639ad479c58259C7"
REACT_APP_ROUTER_ADDRESS = "0xaDa15C4AD1a323c3e58b8198Ea41fCE261937001"
REACT_APP_MULTICALL_ADDR = "0x6e5754A5EE25c1D385cf1e305e27162C54cBA1a5"
REACT_APP_L2_WETH_ADDRESS = "0x6b29C65597Fa2aC80Ab181989969092971f1Fa4e"
